export interface PackagingSolution {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  speed: string;
  filmDiameter: string;
  filmInnerDiameter: string;
  filmWidth: string;
  voltage: string;
  features: string[];
  processSteps: { step: string; label: string }[];
  lineComponents: { id: number; name: string; type: string }[];
  idealFor: string[];
  /** YouTube video ID (e.g. "dQw4w9WgXcQ") — leave empty string if not yet available */
  videoId: string;
}

export const packagingSolutions: PackagingSolution[] = [
  {
    id: "candy",
    name: "Candy Packaging",
    subtitle: "Card Candy Packaging",
    description:
      "High-speed pillow-style flow wrapping — the most popular method for trading card game (TCG) booster packs and collectible card sleeves. Produces a sealed candy-style wrapper at speeds up to 220 bags/min.",
    speed: "20–220 bags/min",
    filmDiameter: "Φ350mm",
    filmInnerDiameter: "76mm",
    filmWidth: "220mm",
    voltage: "AC220V 50Hz 2.9KW",
    features: [
      "Servo-controlled bag length — set and cut, no empty travel",
      "High-sensitivity photoelectric sensor tracking for precise sealing",
      "Up to 60 packaging parameter presets stored on HMI",
      "Anti-misoperation: auto-reverse when product switches",
      "No-film auto-stop to prevent waste",
    ],
    processSteps: [
      { step: "1", label: "Friction Feeder Count" },
      { step: "2", label: "Flow Packing Machine" },
      { step: "3", label: "Checkweigher (NG Rejection)" },
      { step: "4", label: "Manual Cartoning" },
      { step: "5", label: "Case Packing" },
      { step: "6", label: "Shrink Wrapper" },
      { step: "7", label: "H-Type Carton Sealer" },
      { step: "8", label: "Collaborative Palletizing Robot" },
    ],
    lineComponents: [
      { id: 1, name: "Friction Feeder", type: "feeding" },
      { id: 2, name: "Flow Packing Machine", type: "packaging" },
      { id: 3, name: "Sealing & Cutting Shrinkage Machine", type: "packaging" },
      { id: 4, name: "Unpacking Machine", type: "boxing" },
      { id: 5, name: "H-Type Carton Sealer", type: "boxing" },
      { id: 6, name: "Collaborative Palletizing Robot", type: "palletizing" },
    ],
    idealFor: [
      "Trading card booster packs",
      "Collectible card sleeves",
      "Game card multi-packs",
      "Promotional card bundles",
    ],
    videoId: "n_BQVF9rUUc",
  },
  {
    id: "self-adhesive",
    name: "Self-Adhesive Strip Packaging",
    subtitle: "Card Self-Adhesive Strip Packaging",
    description:
      "Reclosable self-adhesive strip bags — ideal for premium card products requiring re-sealability. Each bag features a peel-and-seal strip for repeated opening and closing, protecting card quality during retail display and consumer use.",
    speed: "30–90 packs/min",
    filmDiameter: "Φ450mm",
    filmInnerDiameter: "76mm",
    filmWidth: "350mm (folding film)",
    voltage: "AC380V 50Hz 11.4KW",
    features: [
      "Three sealing methods: self-adhesive, hot-cut, or hot-press",
      "Automatic correction to reduce packaging loss",
      "Anti-air-bag detection — no material, no film wasted",
      "Freely adjustable bag width for multi-spec products",
      "One-click reset and bidirectional position control",
      "Point memory for accurate counting and batch packing",
    ],
    processSteps: [
      { step: "1", label: "Friction Feeder Count" },
      { step: "2", label: "Bagging Machine" },
      { step: "3", label: "Manual Cartoning" },
      { step: "4", label: "Sealing & Cutting Shrinkage" },
      { step: "5", label: "Case Packing" },
      { step: "6", label: "H-Type Carton Sealer" },
      { step: "7", label: "Collaborative Palletizing Robot" },
    ],
    lineComponents: [
      { id: 1, name: "Friction Feeder", type: "feeding" },
      { id: 2, name: "Bagging Machine", type: "packaging" },
      { id: 3, name: "Sealing & Cutting Shrinkage Machine", type: "packaging" },
      { id: 4, name: "Unpacking Machine", type: "boxing" },
      { id: 5, name: "H-Type Carton Sealer", type: "boxing" },
      { id: 6, name: "Collaborative Palletizing Robot", type: "palletizing" },
    ],
    idealFor: [
      "Premium card collector sets",
      "Re-sealable card storage bags",
      "Retail-display card packs",
      "Limited edition card bundles",
    ],
    videoId: "QgwhNnYHxt0",
  },
  {
    id: "four-sides",
    name: "Four-Sides Sealed Packaging",
    subtitle: "Card Four Sides Sealed Packaging",
    description:
      "All-four-edges heat-sealed packaging — delivers a premium, tamper-evident presentation. The fully sealed edges protect against moisture and contamination, making it the preferred choice for high-value trading cards and collectible products.",
    speed: "50–150 packs/min",
    filmDiameter: "Φ350mm",
    filmInnerDiameter: "76mm",
    filmWidth: "250mm",
    voltage: "AC220V 50Hz 9.3KW",
    features: [
      "Seven servo motors for ultra-stable operation",
      "Three-color electric eye tracking for precise text/image alignment",
      "Unique reciprocating cutting & heat-sealing technology",
      "High-speed sealing — firm and stable at 150 packs/min",
      "PLC programmable control with touch-screen HMI",
    ],
    processSteps: [
      { step: "1", label: "Friction Feeder Count" },
      { step: "2", label: "Four-Side Sealing Machine" },
      { step: "3", label: "Cartoning Machine" },
      { step: "4", label: "Bagging & Boxing" },
      { step: "5", label: "Unpacking Machine" },
      { step: "6", label: "H-Type Carton Sealer" },
      { step: "7", label: "Collaborative Palletizing Robot" },
    ],
    lineComponents: [
      { id: 1, name: "Friction Feeder", type: "feeding" },
      { id: 2, name: "Four-Side Sealing Packing Machine", type: "packaging" },
      { id: 3, name: "Cartoning Machine", type: "boxing" },
      { id: 4, name: "Unpacking Machine", type: "boxing" },
      { id: 5, name: "H-Type Carton Sealer", type: "boxing" },
      { id: 6, name: "Collaborative Palletizing Robot", type: "palletizing" },
    ],
    idealFor: [
      "High-value trading cards",
      "Tamper-evident sealed cards",
      "Collectible card premium packs",
      "Moisture-sensitive card products",
    ],
    videoId: "f6Ry7EL5NG8",
  },
  {
    id: "banding",
    name: "Banding Packaging",
    subtitle: "Card Banding Packaging",
    description:
      "Eco-friendly paper band bundling — the most sustainable packaging method for card decks. Uses minimal material while maintaining secure bundling, ideal for board game card decks and standard playing card sets.",
    speed: "5–20 packs/min",
    filmDiameter: "N/A",
    filmInnerDiameter: "N/A",
    filmWidth: "N/A",
    voltage: "AC220V 50Hz 3.0KW",
    features: [
      "Servo motor drive with PLC control and touch screen",
      "Automatic card issuing + belt tying in one operation",
      "Photoelectric control for automatic dispensing & bundling",
      "Multiple function settings: card quantity, material, belt alarm",
      "Product thickness range: 0.1–3mm",
      "Max product size: 100×150mm",
    ],
    processSteps: [
      { step: "1", label: "Friction Feeder Count" },
      { step: "2", label: "Banding Machine" },
      { step: "3", label: "Manual Packing" },
      { step: "4", label: "Cartoning Machine" },
      { step: "5", label: "Unpacking Machine" },
      { step: "6", label: "H-Type Carton Sealer" },
      { step: "7", label: "Collaborative Palletizing Robot" },
    ],
    lineComponents: [
      { id: 1, name: "Friction Feeder", type: "feeding" },
      { id: 2, name: "Banding Machine", type: "packaging" },
      { id: 3, name: "Cartoning Machine", type: "boxing" },
      { id: 4, name: "Unpacking Machine", type: "boxing" },
      { id: 5, name: "H-Type Carton Sealer", type: "boxing" },
      { id: 6, name: "Collaborative Palletizing Robot", type: "palletizing" },
    ],
    idealFor: [
      "Board game card decks",
      "Standard playing card sets",
      "Eco-friendly card packaging",
      "Multi-deck card bundles",
    ],
    videoId: "pTbrqZ8_KWY",
  },
  {
    id: "heat-shrink",
    name: "Heat Shrink Packaging",
    subtitle: "Card Heat Shrink Packaging",
    description:
      "Tight-fitting shrink film wrapping — provides 360° product visibility while offering excellent protection. The shrink film conforms tightly to the product contour, creating a professional retail-ready presentation for card boxes and bundled products.",
    speed: "20–100 bags/min",
    filmDiameter: "Φ300mm",
    filmInnerDiameter: "76mm",
    filmWidth: "590mm",
    voltage: "AC220V 50/60Hz 5.0KW",
    features: [
      "Imported detection photoelectric for thin/small packaging",
      "Automatic feeding with electric eye + timer length adjustment",
      "Sealing knife auto-protection prevents accidental cuts",
      "Film up-down synchronization mechanism corrects deviation",
      "Adjustable hot air direction for beautiful sealing lines",
    ],
    processSteps: [
      { step: "1", label: "Friction Feeder Count" },
      { step: "2", label: "Flow Packing Machine" },
      { step: "3", label: "Shrinking Machine" },
      { step: "4", label: "Manual Cartoning" },
      { step: "5", label: "Case Packing" },
      { step: "6", label: "Unpacking Machine" },
      { step: "7", label: "H-Type Carton Sealer" },
      { step: "8", label: "Collaborative Palletizing Robot" },
    ],
    lineComponents: [
      { id: 1, name: "Friction Feeder", type: "feeding" },
      { id: 2, name: "Flow Packing Machine", type: "packaging" },
      { id: 3, name: "Shrinking Machine", type: "packaging" },
      { id: 4, name: "Cartoning Machine", type: "boxing" },
      { id: 5, name: "Unpacking Machine", type: "boxing" },
      { id: 6, name: "H-Type Carton Sealer", type: "boxing" },
      { id: 7, name: "Collaborative Palletizing Robot", type: "palletizing" },
    ],
    idealFor: [
      "Card box multi-pack bundling",
      "Retail-ready card presentations",
      "Transparent display packaging",
      "Shelf-ready card products",
    ],
    videoId: "PZ_20GogfMc",
  },
  {
    id: "three-dimensional",
    name: "Three-Dimensional Packaging",
    subtitle: "Card Three-Dimensional Packaging",
    description:
      "Box-style 3D wrapping — creates a rigid, box-like package from a single sheet of film. This method delivers a premium presentation with sharp edges and a solid feel, perfect for high-end collector products and gift sets.",
    speed: "40–80 bags/min",
    filmDiameter: "Φ350mm",
    filmInnerDiameter: "76mm",
    filmWidth: "250mm",
    voltage: "AC220V 50Hz 5.5KW",
    features: [
      "Creates rigid, box-like packaging from flat film",
      "Sharp edges and premium presentation",
      "Suitable for thick products (up to 65mm height)",
      "Servo-controlled for consistent quality",
      "PLC programmable with touch-screen interface",
    ],
    processSteps: [
      { step: "1", label: "Friction Feeder Count" },
      { step: "2", label: "Three-Dimensional Packaging Machine" },
      { step: "3", label: "Manual Cartoning" },
      { step: "4", label: "Case Packing" },
      { step: "5", label: "Unpacking Machine" },
      { step: "6", label: "H-Type Carton Sealer" },
      { step: "7", label: "Collaborative Palletizing Robot" },
    ],
    lineComponents: [
      { id: 1, name: "Friction Feeder", type: "feeding" },
      { id: 2, name: "Three-Dimensional Packaging Machine", type: "packaging" },
      { id: 3, name: "Cartoning Machine", type: "boxing" },
      { id: 4, name: "Unpacking Machine", type: "boxing" },
      { id: 5, name: "H-Type Carton Sealer", type: "boxing" },
      { id: 6, name: "Collaborative Palletizing Robot", type: "palletizing" },
    ],
    idealFor: [
      "Premium collector card boxes",
      "Gift set card packaging",
      "High-end product presentation",
      "Limited edition card bundles",
    ],
    videoId: "6cp1MhRoKbo",
  },
];

export interface MachineProduct {
  id: string;
  model: string;
  name: string;
  category: string;
  description: string;
  specs: Record<string, string>;
  applications: string[];
  features: string[];
  /** Product photo path relative to /images/machines/ */
  image: string;
}

export const machineProducts: MachineProduct[] = [
  {
    id: "fkj-100sl",
    model: "FKJ-100SL",
    name: "Automatic Friction Feeder",
    category: "feeding",
    description:
      "High-speed friction feeder for card dispensing. Servo motor driven with PLC control, capable of feeding up to 800 cards/min (CR80 standard). Automatic alarm for missing cards and overfeeding.",
    specs: {
      "Card Thickness": "0.1–3mm",
      "Card Size": "L40–180mm × W30–100mm",
      "Feeding Speed": "800 pcs/min (CR80)",
      "Power": "220V, 450W",
      "Machine Size": "L612 × W382 × H575mm",
      "Weight": "25kg",
    },
    applications: [
      "Postcards, greeting cards, hangtags",
      "Folded manuals and posters",
      "Card books, notebooks, magazines",
    ],
    features: [
      "Servo motor drive, PLC control, touch screen",
      "Max speed 60m/min",
      "Single/multiple/continuous card dispensing",
      "Auto alarm for card leakage and absence",
      "Integrates with automated packaging equipment",
    ],
    image: "/images/machines/fkj-100sl.png",
  },
  {
    id: "fkj-200e",
    model: "FKJ-200E",
    name: "Automatic Friction Feeder",
    category: "feeding",
    description:
      "Medium-format friction feeder for larger card sizes. Feeds up to 500 cards/min with reliable servo control.",
    specs: {
      "Card Thickness": "0.1–3mm",
      "Card Size": "L50–300mm × W61–200mm",
      "Feeding Speed": "500 pcs/min",
      "Power": "220V, 450W",
      "Machine Size": "L711 × W485 × H520mm",
      "Weight": "35kg",
    },
    applications: [
      "Larger format cards and printed materials",
      "Manuals and promotional materials",
      "Medium-sized sheet products",
    ],
    features: [
      "Servo motor drive, PLC control",
      "Reliable medium-speed feeding",
      "Automatic alarm functions",
      "Easy integration with packaging lines",
    ],
    image: "/images/machines/fkj-200e.png",
  },
  {
    id: "fkj-300e",
    model: "FKJ-300E",
    name: "Automatic Friction Feeder",
    category: "feeding",
    description:
      "Large-format friction feeder for oversized cards and sheets. Handles products up to 300×300mm.",
    specs: {
      "Card Thickness": "0.1–3mm",
      "Card Size": "L50–300mm × W100–300mm",
      "Feeding Speed": "300 pcs/min",
      "Power": "220V, 750W",
      "Machine Size": "L711 × W615 × H520mm",
      "Weight": "45kg",
    },
    applications: [
      "Large format cards and board game components",
      "Oversized printed materials",
      "Game boards and large cards",
    ],
    features: [
      "Handles large-format products",
      "Servo controlled precision",
      "Photoelectric sensing control",
      "PLC programmable operation",
    ],
    image: "/images/machines/fkj-300e.png",
  },
  {
    id: "fkj-420e",
    model: "FKJ-420E",
    name: "Automatic Friction Feeder",
    category: "feeding",
    description:
      "Extra-wide friction feeder for products up to 420mm width. Designed for board game boards and large format materials.",
    specs: {
      "Card Thickness": "1–3mm",
      "Card Size": "L100–300mm × W180–420mm",
      "Feeding Speed": "200 pcs/min",
      "Power": "220V, 750W",
      "Machine Size": "L711 × W735 × H520mm",
      "Weight": "58kg",
    },
    applications: [
      "Board game boards and large components",
      "Extra-wide printed materials",
      "Multi-page book-type products",
    ],
    features: [
      "Extra-wide feeding capacity",
      "Stable servo operation",
      "Easy touch-screen control",
      "Robust construction for thick materials",
    ],
    image: "/images/machines/fkj-420e.png",
  },
  {
    id: "three-head-suction",
    model: "Three-Head Planetary",
    name: "Card Suction Machine",
    category: "feeding",
    description:
      "Planetary suction cup card dispenser for delicate or thin cards. Three sets of suction cups rotate counterclockwise to pick and feed cards individually — ideal for game cards and films that friction feeders may damage.",
    specs: {
      "Card Thickness": "0.1–2mm",
      "Card Size": "L20–120mm × W20–120mm",
      "Feeding Speed": "120 pcs/min",
      "Power": "220V, 1.9KW",
      "Machine Size": "L700 × W500 × H600mm",
      "Weight": "120kg",
    },
    applications: [
      "Game cards and TCG cards",
      "Thin plastic cards and films",
      "Deformable sheet products",
    ],
    features: [
      "Three-head planetary suction mechanism",
      "Panasonic pressure detection switch",
      "No-card automatic alarm",
      "Servo motor with PLC control",
    ],
    image: "/images/machines/three-head-suction.png",
    },
  {
    id: "four-head-suction",
    model: "Four-Head Planetary",
    name: "Card Suction Machine",
    category: "feeding",
    description:
      "High-speed four-head planetary suction machine. Four suction stations operating simultaneously for maximum throughput up to 280 pcs/min.",
    specs: {
      "Card Thickness": "0.1–1mm",
      "Card Size": "L80–150mm × W50–180mm",
      "Feeding Speed": "280 pcs/min",
      "Power": "220V, 2.0KW",
      "Machine Size": "L1300 × W800 × H1500mm",
      "Weight": "150kg",
    },
    applications: [
      "High-speed card production lines",
      "Large-volume card packaging",
      "Premium card products requiring gentle handling",
    ],
    features: [
      "Four-head simultaneous operation",
      "Maximum throughput for high-volume lines",
      "Servo precision control",
      "Real-time pressure monitoring",
    ],
    image: "/images/machines/four-head-suction.png",
    },
  {
    id: "card-dispensing-matching",
    model: "CDM-100",
    name: "Card Dispensing Matching System",
    category: "feeding",
    description:
      "Intelligent multi-station card dispensing system with computer control. Automatically sorts and dispatches cards according to pre-set recipes, supporting up to 25,000 packs per batch.",
    specs: {
      "Card Thickness": "0.3–1mm",
      "Card Size": "L88–104mm × W63–79mm",
      "Feeding Speed": "60–80 pcs/min (single channel)",
      "Power": "220V, 2.0KW",
      "Machine Size": "L1900 × W1600 × H900mm",
      "Weight": "300kg",
    },
    applications: [
      "Multi-card pack assembly (TCG, CCG)",
      "Complex card sorting and matching",
      "Batch production with variable recipes",
    ],
    features: [
      "Computer-controlled dispatching system",
      "EXCEL recipe editing for card sorting",
      "Over 1,000 process recipe files storable",
      "Ultrasonic dual-sheet / visual / thickness detection",
      "Up to 25,000 packs per batch run",
    ],
    image: "/images/machines/card-dispensing-matching.png",
    },
  {
    id: "zs-220x",
    model: "ZS-220X",
    name: "High-Speed Servo Packaging Machine",
    category: "packaging",
    description:
      "Compact high-speed pillow packaging machine. Servo controlled with up to 220 bags/min output, ideal for candy-style card wrapping.",
    specs: {
      "Packaging Speed": "20–220 bags/min",
      "Film Width": "Max 220mm",
      "Bag Length": "60–1000mm",
      "Bag Width": "30–90mm",
      "Product Height": "5–35mm",
      "Roll Film Diameter": "Max 300mm",
      "Power": "220V, 50/60Hz, 2.9KW",
      "Machine Size": "L4117 × W820 × H1544mm",
      "Weight": "450kg",
    },
    applications: [
      "Card candy packaging",
      "Small irregular item packaging",
      "Food and printed product packaging",
    ],
    features: [
      "Servo control — set bag length, cut, no empty travel",
      "60 packaging parameter presets",
      "High-sensitivity photoelectric sensor tracking",
      "Anti-misoperation auto-reverse",
      "No-film auto-stop protection",
    ],
    image: "/images/machines/zs-220x.png",
    },
  {
    id: "sbf-250",
    model: "SBF-250",
    name: "Four-Side Sealing Servo Packaging Machine",
    category: "packaging",
    description:
      "High-speed four-side sealing machine. Seven servo motors drive stable operation at up to 150 packs/min, with precise three-color electric eye tracking.",
    specs: {
      "Packaging Speed": "50–150 bags/min",
      "Film Width": "250mm",
      "Product Size": "L100–200mm × W100–250mm",
      "Product Height": "1–10mm",
      "Roll Film Diameter": "Max 350mm",
      "Power": "220V, 50Hz, 9.3KW",
      "Machine Size": "L5148 × W876 × H1800mm",
      "Weight": "1200kg",
    },
    applications: [
      "Card four-side sealed packaging",
      "Premium product packaging",
      "Tamper-evident packaging",
    ],
    features: [
      "Seven servo motors for stable operation",
      "Three-color electric eye tracking",
      "Reciprocating cutting & heat-sealing technology",
      "PLC programmable control",
    ],
    image: "/images/machines/sbf-250.png",
    },
  {
    id: "qdzd-2130",
    model: "QDZD-2130",
    name: "Automatic Bagging Machine",
    category: "packaging",
    description:
      "Self-adhesive strip bagging machine for card products. Supports three sealing methods: self-adhesive, hot-cut, and hot-press.",
    specs: {
      "Packaging Speed": "30–90 bags/min",
      "Film Width": "350mm",
      "Bag Length": "70–300mm",
      "Bag Width": "60–210mm",
      "Product Height": "0.1–35mm",
      "Roll Film Diameter": "Max 450mm",
      "Power": "380V, 50Hz, 11.7KW",
      "Machine Size": "L3752 × W4000 × H1854mm",
      "Weight": "1400kg",
    },
    applications: [
      "Card self-adhesive strip packaging",
      "Premium re-sealable card bags",
      "Retail display packaging",
    ],
    features: [
      "Three sealing methods available",
      "Automatic correction function",
      "Anti-air-bag detection",
      "One-click reset and bidirectional control",
      "Suction cup bag retrieval",
    ],
    image: "/images/machines/qdzd-2130.png",
    },
  {
    id: "pof-shrink",
    model: "POF-Series",
    name: "Automatic POF Film Wrapping & Sealing Machine",
    category: "packaging",
    description:
      "POF shrink wrapping machine for professional retail packaging. Equipped with imported detection photoelectric and sealing knife auto-protection.",
    specs: {
      "Packaging Speed": "15–30 bags/min",
      "Conveyor Speed": "26m/min",
      "Sealing Knife Size": "630(L) × 465(W)mm",
      "Package Size": "L90–560 × W50–380 × H10–180mm",
      "Power": "220V, 2.5KW",
      "Machine Size": "L1898 × W1125 × H1568mm",
      "Weight": "250kg",
    },
    applications: [
      "Card shrink wrapping",
      "Retail-ready card packaging",
      "Multi-product bundling",
    ],
    features: [
      "Imported detection photoelectric",
      "Teflon-coated high-temp alloy sealing knife",
      "Film up-down synchronization mechanism",
      "Sealing knife auto-protection",
    ],
    image: "/images/machines/pof-shrink.png",
    },
  {
    id: "cartoning",
    model: "BX-Series",
    name: "Fully Automatic Box Packing Machine",
    category: "boxing",
    description:
      "Automatic cartoning machine for boxed card products. Handles feeding, opening, inserting, and sealing at 20–45 boxes/min.",
    specs: {
      "Encasing Speed": "20–45 boxes/min",
      "Box Dimension": "L200–410 × W30–60 × H30–60mm",
      "Power": "380V, 50Hz, 4KW",
      "Machine Size": "L4300 × W1600 × H1900mm",
      "Weight": "1600kg",
    },
    applications: [
      "Card product cartoning",
      "Pharmaceutical and food boxing",
      "Daily chemical product packaging",
    ],
    features: [
      "Automatic feeding, opening, inserting, sealing",
      "Servo/stepper motor + PLC control",
      "Photoelectric detection — empty bags not boxed",
      "No mold change needed for different sizes",
    ],
    image: "/images/machines/cartoning.png",
    },
  {
    id: "carton-forming",
    model: "CF-Series",
    name: "Automatic Carton Forming & Sealing Machine",
    category: "boxing",
    description:
      "Carton case former with automatic bottom tape sealing. Vertical storage design allows replenishment without stopping production.",
    specs: {
      "Speed": "8–10 boxes/min",
      "Carton Size": "L200–450 × W150–400 × H100–400mm",
      "Power": "220V, 50/60Hz, 240W",
      "Machine Size": "L2000 × W1900 × H1450mm",
      "Weight": "450kg",
    },
    applications: [
      "Card product case forming",
      "Multi-industry carton forming",
      "Automated case erecting",
    ],
    features: [
      "Suck, form, and seal in one go",
      "Vertical storage — replenish without stopping",
      "PLC & HMI touch screen control",
      "Customized size design available",
    ],
    image: "/images/machines/carton-forming.png",
    },
  {
    id: "h-type-sealer",
    model: "HT-Series",
    name: "Automatic H-Type Carton Sealing Machine",
    category: "boxing",
    description:
      "H-type carton sealer for top, bottom, and corner taping. 90° turning mechanism pushes case into four-corner edge sealing.",
    specs: {
      "Speed": "10–15 boxes/min",
      "Carton Size": "L180–500mm (adjustable)",
      "Power": "220V, 50/60Hz",
      "Weight": "450kg",
    },
    applications: [
      "Card product case sealing",
      "Industrial carton sealing",
      "Four-corner tape sealing",
    ],
    features: [
      "Top & bottom tape sealing automatically",
      "90° turning for four-corner sealing",
      "Novel and precise structural design",
      "Manual width/height adjustment",
    ],
    image: "/images/machines/h-type-sealer.png",
    },
  {
    id: "palletizing-robot",
    model: "KKMD-30L",
    name: "Intelligent Collaborative Palletizing Robot",
    category: "palletizing",
    description:
      "Collaborative palletizing robot with 30kg payload and 1800mm working radius. Safe for human cooperation — stops immediately when personnel get too close.",
    specs: {
      "Load": "0–30kg",
      "Working Radius": "1800mm",
      "Stacking Height": "1600–2100mm",
      "Pallet Size": "L1200 × W1200mm",
      "Power": "220V, 4.0KW",
      "Machine Size": "L1800 × W1500 × H2500mm",
      "Weight": "500kg",
    },
    applications: [
      "Card product case palletizing",
      "Multi-industry palletizing",
      "Collaborative end-of-line automation",
    ],
    features: [
      "Installation & debugging in 3 hours",
      "100+ palletizing formulas storable",
      "Left/right simultaneous stacking patterns",
      "Personnel collision prevention",
      "Power-off suction cup safety — material won't fall",
    ],
    image: "/images/machines/palletizing-robot.png",
    },
  {
    id: "ai-visual",
    model: "KKR-C02",
    name: "AI Card Visual Inspection System",
    category: "ai",
    description:
      "AI-powered card inspection system with OCR and mixed-order detection. Detects wrong cards, missing cards, and out-of-sequence cards at speeds over 400 sheets/min with 100% error detection rate.",
    specs: {
      "Card Size": "100 × 150mm",
      "Card Thickness": "2mm",
      "Checking Speed": "400 bags/min",
      "Checking Accuracy": "Min 5×5mm region",
      "Power": "220V, 50/60Hz, 0.6KW",
      "Weight": "10–15kg",
    },
    applications: [
      "Card error detection in production lines",
      "OCR character verification",
      "Mixed-order and sequence detection",
      "Quality assurance for card packaging",
    ],
    features: [
      "100% error detection rate (5×5mm minimum)",
      "Real-time detection over 400 sheets/min",
      "AI self-training for new card templates",
      "OCR character detection (Chinese, English, numbers)",
      "Mixed-order detection in 100ms",
      "New batch training in as fast as 3 minutes",
    ],
    image: "/images/machines/ai-visual.png",
  },
];

export const companyInfo = {
  name: "Guangzhou Chanfer Intelligent Equipment Co., Ltd",
  shortName: "CHANFER",
  brandName: "CUKKE",
  founded: 2011,
  experience: "25+",
  clients: "8000+",
  patents: "100+",
  employees: "100+",
  factoryArea: "12000m²",
  certifications: [
    "National High-Tech Enterprise",
    "Specialized, Refined, Unique & New Enterprise",
    "ISO9001 Quality Management System",
    "CE Certification",
  ],
  address: {
    street: "701, No.5 Yongfeng Road, Shawan Street",
    district: "Panyu District",
    city: "Guangzhou",
    province: "Guangdong",
    country: "China",
  },
  dongguanAddress: {
    street: "2F, Building 6, No.10 QiaoXin West Second Road",
    district: "Qiaotou Town",
    city: "Dongguan",
    province: "Guangdong",
    country: "China",
  },
  contact: {
    phone: "+86-20-84821674",
    mobile: "+86 13060985132",
    email: "sarah@gzchanfer.com",
    website: "www.gzchanfer.com",
    dongguanPhone: "0769-8119-0573",
  },
  social: {
    youtube: "CHANFER",
    tiktok: "CHANFER",
    facebook: "CHANFER",
    wechat: "CHANFER",
    whatsapp: "+86 13060985132",
  },
  tagline: "Everything Can Be Packed",
  taglines: {
    washing: "Washing Liquid Automatic Packaging Solution",
    gameCards: "Game Cards / Board Game Automatic Packaging Solution",
  },
  milestones: [
    { year: "2011", event: "Company established in Dongguan; developed first card issuing machine" },
    { year: "2014", event: "Obtained first patent; accumulated annual sales of 500 units" },
    { year: "2015", event: "Strengthened servo pillow packaging business; Established CUKKE brand" },
    { year: "2016", event: "Developed self-adhesive strip bagging machine; Launched card packaging line" },
    { year: "2018", event: "Obtained National High-Tech Enterprise Certificate" },
    { year: "2021", event: "Integrated solution for box packaging" },
    { year: "2022", event: "Introduced ISO9001 Quality Management System" },
    { year: "2023", event: 'Awarded "Specialized, Refined, Unique & New" SME recognition' },
    { year: "2024", event: "Relocated to Wanjin High-Tech Industrial Park; Established Yiwu Branch" },
    { year: "2025", event: "Established Guangzhou branch; Founded AI Visual Application Center" },
  ],
  partners: [
    "CASELL", "RR DONNELLEY", "YUTO", "QP Group",
    "姚記", "裕同科技", "当纳利印刷", "金光集团",
    "金杯印刷", "SINARMAS", "HUNG HING", "KINARY",
    "LEO PAPER GROUP", "LONG XING GROUP",
  ],
};
