import json

base_dir = 'C:/Users/Sarah/WorkBuddy/2026-06-11-17-27-29/cfpack-site/messages'

# English - same as data.ts defaults
en_data = {
    "candy": {
        "name": "Candy Packaging", "subtitle": "Card Candy Packaging",
        "description": "High-speed pillow-style flow wrapping — the most popular method for trading card game (TCG) booster packs and collectible card sleeves. Produces a sealed candy-style wrapper at speeds up to 220 bags/min.",
        "features": ["Servo-controlled bag length — set and cut, no empty travel","High-sensitivity photoelectric sensor tracking for precise sealing","Up to 60 packaging parameter presets stored on HMI","Anti-misoperation: auto-reverse when product switches","No-film auto-stop to prevent waste"],
        "processSteps": {"1":"Friction Feeder Count","2":"Flow Packing Machine","3":"Checkweigher (NG Rejection)","4":"Manual Cartoning","5":"Case Packing","6":"Shrink Wrapper","7":"H-Type Carton Sealer","8":"Collaborative Palletizing Robot"},
        "lineComponents": {"Friction Feeder":"Friction Feeder","Flow Packing Machine":"Flow Packing Machine","Sealing & Cutting Shrinkage Machine":"Sealing & Cutting Shrinkage Machine","Unpacking Machine":"Unpacking Machine","H-Type Carton Sealer":"H-Type Carton Sealer","Collaborative Palletizing Robot":"Collaborative Palletizing Robot"},
        "idealFor": ["Trading card booster packs","Collectible card sleeves","Game card multi-packs","Promotional card bundles"]
    },
    "self-adhesive": {
        "name": "Self-Adhesive Strip Packaging", "subtitle": "Card Self-Adhesive Strip Packaging",
        "description": "Reclosable self-adhesive strip bags — ideal for premium card products requiring re-sealability. Each bag features a peel-and-seal strip for repeated opening and closing, protecting card quality during retail display and consumer use.",
        "features": ["Three sealing methods: self-adhesive, hot-cut, or hot-press","Automatic correction to reduce packaging loss","Anti-air-bag detection — no material, no film wasted","Freely adjustable bag width for multi-spec products","One-click reset and bidirectional position control","Point memory for accurate counting and batch packing"],
        "processSteps": {"1":"Friction Feeder Count","2":"Bagging Machine","3":"Manual Cartoning","4":"Sealing & Cutting Shrinkage","5":"Case Packing","6":"H-Type Carton Sealer","7":"Collaborative Palletizing Robot"},
        "lineComponents": {"Friction Feeder":"Friction Feeder","Bagging Machine":"Bagging Machine","Sealing & Cutting Shrinkage Machine":"Sealing & Cutting Shrinkage Machine","Unpacking Machine":"Unpacking Machine","H-Type Carton Sealer":"H-Type Carton Sealer","Collaborative Palletizing Robot":"Collaborative Palletizing Robot"},
        "idealFor": ["Premium card collector sets","Re-sealable card storage bags","Retail-display card packs","Limited edition card bundles"]
    },
    "four-sides": {
        "name": "Four-Sides Sealed Packaging", "subtitle": "Card Four Sides Sealed Packaging",
        "description": "All-four-edges heat-sealed packaging — delivers a premium, tamper-evident presentation. The fully sealed edges protect against moisture and contamination, making it the preferred choice for high-value trading cards and collectible products.",
        "features": ["Seven servo motors for ultra-stable operation","Three-color electric eye tracking for precise text/image alignment","Unique reciprocating cutting & heat-sealing technology","High-speed sealing — firm and stable at 150 packs/min","PLC programmable control with touch-screen HMI"],
        "processSteps": {"1":"Friction Feeder Count","2":"Four-Side Sealing Machine","3":"Cartoning Machine","4":"Bagging & Boxing","5":"Unpacking Machine","6":"H-Type Carton Sealer","7":"Collaborative Palletizing Robot"},
        "lineComponents": {"Friction Feeder":"Friction Feeder","Four-Side Sealing Packing Machine":"Four-Side Sealing Packing Machine","Cartoning Machine":"Cartoning Machine","Unpacking Machine":"Unpacking Machine","H-Type Carton Sealer":"H-Type Carton Sealer","Collaborative Palletizing Robot":"Collaborative Palletizing Robot"},
        "idealFor": ["High-value trading cards","Tamper-evident sealed cards","Collectible card premium packs","Moisture-sensitive card products"]
    },
    "banding": {
        "name": "Banding Packaging", "subtitle": "Card Banding Packaging",
        "description": "Eco-friendly paper band bundling — the most sustainable packaging method for card decks. Uses minimal material while maintaining secure bundling, ideal for board game card decks and standard playing card sets.",
        "features": ["Servo motor drive with PLC control and touch screen","Automatic card issuing + belt tying in one operation","Photoelectric control for automatic dispensing & bundling","Multiple function settings: card quantity, material, belt alarm","Product thickness range: 0.1–3mm","Max product size: 100×150mm"],
        "processSteps": {"1":"Friction Feeder Count","2":"Banding Machine","3":"Manual Packing","4":"Cartoning Machine","5":"Unpacking Machine","6":"H-Type Carton Sealer","7":"Collaborative Palletizing Robot"},
        "lineComponents": {"Friction Feeder":"Friction Feeder","Banding Machine":"Banding Machine","Cartoning Machine":"Cartoning Machine","Unpacking Machine":"Unpacking Machine","H-Type Carton Sealer":"H-Type Carton Sealer","Collaborative Palletizing Robot":"Collaborative Palletizing Robot"},
        "idealFor": ["Board game card decks","Standard playing card sets","Eco-friendly card packaging","Multi-deck card bundles"]
    },
    "heat-shrink": {
        "name": "Heat Shrink Packaging", "subtitle": "Card Heat Shrink Packaging",
        "description": "Tight-fitting shrink film wrapping — provides 360° product visibility while offering excellent protection. The shrink film conforms tightly to the product contour, creating a professional retail-ready presentation for card boxes and bundled products.",
        "features": ["Imported detection photoelectric for thin/small packaging","Automatic feeding with electric eye + timer length adjustment","Sealing knife auto-protection prevents accidental cuts","Film up-down synchronization mechanism corrects deviation","Adjustable hot air direction for beautiful sealing lines"],
        "processSteps": {"1":"Friction Feeder Count","2":"Flow Packing Machine","3":"Shrinking Machine","4":"Manual Cartoning","5":"Case Packing","6":"Unpacking Machine","7":"H-Type Carton Sealer","8":"Collaborative Palletizing Robot"},
        "lineComponents": {"Friction Feeder":"Friction Feeder","Flow Packing Machine":"Flow Packing Machine","Shrinking Machine":"Shrinking Machine","Cartoning Machine":"Cartoning Machine","Unpacking Machine":"Unpacking Machine","H-Type Carton Sealer":"H-Type Carton Sealer","Collaborative Palletizing Robot":"Collaborative Palletizing Robot"},
        "idealFor": ["Card box multi-pack bundling","Retail-ready card presentations","Transparent display packaging","Shelf-ready card products"]
    },
    "three-dimensional": {
        "name": "Three-Dimensional Packaging", "subtitle": "Card Three-Dimensional Packaging",
        "description": "Box-style 3D wrapping — creates a rigid, box-like package from a single sheet of film. This method delivers a premium presentation with sharp edges and a solid feel, perfect for high-end collector products and gift sets.",
        "features": ["Creates rigid, box-like packaging from flat film","Sharp edges and premium presentation","Suitable for thick products (up to 65mm height)","Servo-controlled for consistent quality","PLC programmable with touch-screen interface"],
        "processSteps": {"1":"Friction Feeder Count","2":"Three-Dimensional Packaging Machine","3":"Manual Cartoning","4":"Case Packing","5":"Unpacking Machine","6":"H-Type Carton Sealer","7":"Collaborative Palletizing Robot"},
        "lineComponents": {"Friction Feeder":"Friction Feeder","Three-Dimensional Packaging Machine":"Three-Dimensional Packaging Machine","Cartoning Machine":"Cartoning Machine","Unpacking Machine":"Unpacking Machine","H-Type Carton Sealer":"H-Type Carton Sealer","Collaborative Palletizing Robot":"Collaborative Palletizing Robot"},
        "idealFor": ["Premium collector card boxes","Gift set card packaging","High-end product presentation","Limited edition card bundles"]
    }
}

# Russian
ru_data = {
    "candy": {
        "name": "Конфетная упаковка", "subtitle": "Упаковка карт в конфету",
        "description": "Высокоскоростная flow-упаковка в виде подушки — самый популярный метод для бустерпаков TCG и защитных конвертов для коллекционных карт. Производит запечатанную конфетную обертку со скоростью до 220 пакетов/мин.",
        "features": ["Сервоуправление длины пакета — установка и резка без холостого хода","Высокочувствительный фотоэлектрический датчик слежения","До 60 пресетов параметров упаковки на HMI","Защита от ошибок: автореверс при смене продукта","Автоостановка при отсутствии пленки"],
        "processSteps": {"1":"Подача трением с подсчетом","2":"Flow-упаковочная машина","3":"Весоконтроль (брак)","4":"Ручная укладка в коробки","5":"Упаковка в ящики","6":"Термоусадка","7":"Н-образный коробкозакрыватель","8":"Кооперативный паллетирующий робот"},
        "lineComponents": {"Friction Feeder":"Подающее устройство трением","Flow Packing Machine":"Flow-упаковочная машина","Sealing & Cutting Shrinkage Machine":"Машина запечатывания и резки усадки","Unpacking Machine":"Распаковщик","H-Type Carton Sealer":"Н-образный коробкозакрыватель","Collaborative Palletizing Robot":"Кооперативный робот паллетирования"},
        "idealFor": ["Бустерпаки TCG","Защитные конверты для карт","Мультипаки игровых карт","Промо-комплекты карт"]
    },
    "self-adhesive": {
        "name": "Упаковка с самоклеящейся полосой", "subtitle": "Упаковка карт с самоклеящейся полосой",
        "description": "Повторно закрывающиеся пакеты с самоклеящейся полосой — идеально для премиальных карточных продуктов требующих повторной герметичности. Каждый пакет имеет отклеиваемую самоклеящуюся полосу для многократного открытия и закрытия.",
        "features": ["Три метода запечатывания: самоклеящийся, горячая резка или горячее прессование","Автоматическая коррекция для снижения потерь при упаковке","Обнаружение пустых пакетов — нет продукта, нет потерь пленки","Свободная регулировка ширины пакета","Одноклик сброс и двунаправленное управление позиционированием","Память точек для точного счета и пакетирования"],
        "processSteps": {"1":"Подача трением с подсчетом","2":"Машина фасовки в пакеты","3":"Ручная укладка в коробки","4":"Запечатывание и резка усадки","5":"Упаковка в ящики","6":"Н-образный коробкозакрыватель","7":"Кооперативный паллетирующий робот"},
        "lineComponents": {"Friction Feeder":"Подающее устройство трением","Bagging Machine":"Машина фасовки в пакеты","Sealing & Cutting Shrinkage Machine":"Машина запечатывания и резки усадки","Unpacking Machine":"Распаковщик","H-Type Carton Sealer":"Н-образный коробкозакрыватель","Collaborative Palletizing Robot":"Кооперативный робот паллетирования"},
        "idealFor": ["Коллекционные наборы карт","Повторно закрывающиеся пакеты для хранения карт","Розничные упаковки карт","Лимитированные комплекты карт"]
    },
    "four-sides": {
        "name": "Четырехсторонняя упаковка", "subtitle": "Четырехсторонняя упаковка карт",
        "description": "Тепловое запечатывание всех четырех краев — премиумное представление с защитой от вскрытия. Полностью запечатанные края защищают от влаги и загрязнения.",
        "features": ["Семь сервомоторов для сверхстабильной работы","Трехцветная электрическая глаз для точного выравнивания текста/изображений","Уникальная технология возвратно-поступательной резки и термосварки","Высокоскоростная сварка — прочная и стабильная при 150 пакетах/мин","PLC программируемое управление с сенсорным экраном"],
        "processSteps": {"1":"Подача трением с подсчетом","2":"Машина четырехсторонней сварки","3":"Машина автоматической укладки в коробки","4":"Фасовка и упаковка в коробку","5":"Распаковщик","6":"Н-образный коробкозакрыватель","7":"Кооперативный паллетирующий робот"},
        "lineComponents": {"Friction Feeder":"Подающее устройство трением","Four-Side Sealing Packing Machine":"Машина четырехсторонней сварки","Cartoning Machine":"Машина автоматической укладки в коробки","Unpacking Machine":"Распаковщик","H-Type Carton Sealer":"Н-образный коробкозакрыватель","Collaborative Palletizing Robot":"Кооперативный робот паллетирования"},
        "idealFor": ["Карты высокой стоимости","Защита от вскрытия","Премиум упаковка коллекционных карт","Влагочувствительные продукты"]
    },
    "banding": {
        "name": "Бандажная упаковка", "subtitle": "Бандажная упаковка карт",
        "description": "Экологичная бумажная лента для связывания — самый устойчивый метод упаковки колод карт. Использует минимальное количество материалов при надежном связывании.",
        "features": ["Привод сервомотора с PLC управлением и сенсорным экраном","Автоматическая выдача карт + перевязывание лентой за одну операцию","Фотоэлектрическое управление автоматической выдачей","Многофункциональные настройки: количество карт, материал, сигнал ленты","Диапазон толщины продукта: 0,1–3 мм","Максимальный размер продукта: 100×150 мм"],
        "processSteps": {"1":"Подача трением с подсчетом","2":"Машина бандажа","3":"Ручная раскладка","4":"Машина автоматической укладки в коробки","5":"Распаковщик","6":"Н-образный коробкозакрыватель","7":"Кооперативный паллетирующий робот"},
        "lineComponents": {"Friction Feeder":"Подающее устройство трением","Banding Machine":"Машина бандажа","Cartoning Machine":"Машина автоматической укладки в коробки","Unpacking Machine":"Распаковщик","H-Type Carton Sealer":"Н-образный коробкозакрыватель","Collaborative Palletizing Robot":"Кооперативный робот паллетирования"},
        "idealFor": ["Колоды настольных игр","Стандартные колоды игральных карт","Экологичная упаковка карт","Многоколодные комплекты"]
    },
    "heat-shrink": {
        "name": "Термоусадочная упаковка", "subtitle": "Термоусадочная упаковка карт",
        "description": "Плотная усадочная пленка — обеспечивает 360° видимости продукта при отличной защите. Пленка плотно облегает контур продукта, создавая профессиональную розничную презентацию.",
        "features": ["Импортный фотоэлектрический детектор для тонкой/мелкой упаковки","Автоматическая подача с электроглазом + регулировкой длины по таймеру","Автозащита ножа запечатывания от случайных порезов","Синхронизация пленки сверху и снизу исправляет отклонение","Регулируемое направление горячего воздуха"],
        "processSteps": {"1":"Подача трением с подсчетом","2":"Flow-упаковочная машина","3":"Термоусадочная печь","4":"Ручная укладка в коробки","5":"Упаковка в ящики","6":"Распаковщик","7":"Н-образный коробкозакрыватель","8":"Кооперативный паллетирующий робот"},
        "lineComponents": {"Friction Feeder":"Подающее устройство трением","Flow Packing Machine":"Flow-упаковочная машина","Shrinking Machine":"Термоусадочная печь","Cartoning Machine":"Машина автоматической укладки в коробки","Unpacking Machine":"Распаковщик","H-Type Carton Sealer":"Н-образный коробкозакрыватель","Collaborative Palletizing Robot":"Кооперативный робот паллетирования"},
        "idealFor": ["Мультипаковка коробок с картами","Готовые к рознице презентации","Прозрачная демонстрационная упаковка","Продукты готовые к полке"]
    },
    "three-dimensional": {
        "name": "Трехмерная упаковка", "subtitle": "Трехмерная упаковка карт",
        "description": "Коробочный 3D-заворот — создает жесткую коробкообразную упаковку из одного листа пленки. Премиальное представление с острыми краями и прочным ощущением.",
        "features": ["Создает жесткую коробкообразную упаковку из плоской пленки","Острые края и премиум представление","Подходит для толстых продуктов (до 65 мм высоты)","Сервоуправление для стабильного качества","PLC программируемый с сенсорным интерфейсом"],
        "processSteps": {"1":"Подача трением с подсчетом","2":"Машина трехмерной упаковки","3":"Ручная укладка в коробки","4":"Упаковка в ящики","5":"Распаковщик","6":"Н-образный коробкозакрыватель","7":"Кооперативный паллтирующий робот"},
        "lineComponents": {"Friction Feeder":"Подающее устройство трением","Three-Dimensional Packaging Machine":"Машина трехмерной упаковки","Cartoning Machine":"Машина автоматической укладки в коробки","Unpacking Machine":"Распаковщик","H-Type Carton Sealer":"Н-образный коробкозакриватель","Collaborative Palletizing Robot":"Кооперативный робот паллетирования"},
        "idealFor": ["Премиум коллекционные коробки","Подарочные наборы карт","Премиум презентация продуктов","Лимитированные комплекты карт"]
    }
}

# Italian
it_data = {
    "candy": {"name":"Imballaggio Caramella","subtitle":"Imballaggio Caramella Carte","description":"Incarto flow ad alta velocità — il metodo più popolare per i pacchetti booster di giochi di carte collezionabili (TCG) e le bustine protettive. Produce una confezione sigillata tipo caramella fino a 220 sacchetti/min.","features":["Lunghezza sacchetto controllata da servomotore — imposta e taglia, nessun vuoto di corsa","Sensore fotoelettrico ad alta sensibilità per saldatura precisa","Fino a 60 preimpostazioni parametri imballaggio su HMI","Protezione contro errori: inversione automatica al cambio prodotto","Arresto automatico senza film per evitare sprechi"],"processSteps":{"1":"Conteggio alimentatore a frizione","2":"Macchina incarto flow","3":"Pesatura (scarto NG)","4":"Confezionamento manuale in scatole","5":"Imballaggio in casi","6":"Ricciolo termico","7":"Sigillascatola a H","8":"Robot collaborativo pallettizzazione"},"lineComponents":{"Friction Feeder":"Alimentatore a frizione","Flow Packing Machine":"Macchina incarto flow","Sealing & Cutting Shrinkage Machine":"Macchina sigillatura e taglio ricciolo","Unpacking Machine":"Disimballatrice","H-Type Carton Sealer":"Sigillascatola a H","Collaborative Palletizing Robot":"Robot collaborativo pallettizzazione"},"idealFor":["Pacchi booster di carte collezionabili","Bustine protettive carte","Multipack di carte gioco","Bundle promozionali"]},
    "self-adhesive": {"name":"Imballaggio a Striscia Autoadesiva","subtitle":"Imballaggio a Striscia Autoadesiva Carte","description":"Sacchetti richiudibili con striscia autoadesiva — ideali per prodotti carte premium che richiedono risigillabilità. Ogni sacchetto presenta una striscia stacca-sigilla per apertura e chiusura ripetuta.","features":["Tre metodi di sigillatura: autoadesiva, taglio caldo o pressa calda","Correzione automatica per ridurre perdite di imballaggio","Rilevamento sacchetti vuoti — nessun materiale, nessuno spreco film","Larghezza sacchetto liberamente regolabile per prodotti multiformato","Reset con un clic e controllo posizione bidirezionale","Memoria punto per conteggio preciso e imballo batch"],"processSteps":{"1":"Conteggio alimentatore a frizione","2":"Macchina imbustamento","3":"Confezionamento manuale in scatole","4":"Sigillatura e taglio ricciolo","5":"Imballaggio in casi","6":"Sigillascatola a H","7":"Robot collaborativo pallettizzazione"},"lineComponents":{"Friction Feeder":"Alimentatore a frizione","Bagging Machine":"Macchina imbustamento","Sealing & Cutting Shrinkage Machine":"Macchina sigillatura e taglio ricciolo","Unpacking Machine":"Disimballatrice","H-Type Carton Sealer":"Sigillascatola a H","Collaborative Palletizing Robot":"Robot collaborativo pallettizzazione"},"idealFor":["Set collezione carte premium","Sacchetti stoccaggio carte richiudibili","Pacchetti esposizione vendita","Bundle edizione limitata"]},
    "four-sides": {"name":"Imballaggio Quattro Lati Sigillati","subtitle":"Imballaggio Quattro Lati Sigillati Carte","description":"Sigillatura termica tutti e quattro lati — presentazione premium anti-manomissione. I bordi completamente sigillati proteggono da umidità e contaminazione.","features":["Sette servomotori per funzionamento ultrastabile","Occhio elettrico tricolore per allineamento testo/immagine","Tecnologia unica di taglio e saldatura reciproca","Sigillatura ad alta velocità — solida e stabile a 150 sacchetti/min","Controllo PLC programmabile con schermo tattile"],"processSteps":{"1":"Conteggio alimentatore a frizione","2":"Macchina sigillatura quattro lati","3":"Macchina confezionamento scatole","4":"Imbustamento e inscatolamento","5":"Disimballatrice","6":"Sigillascatola a H","7":"Robot collaborativo pallettizzazione"},"lineComponents":{"Friction Feeder":"Alimentatore a frizione","Four-Side Sealing Packing Machine":"Macchina sigillatura quattro lati","Cartoning Machine":"Macchina confezionamento scatole","Unpacking Machine":"Disimballatrice","H-Type Carton Sealer":"Sigillascatola a H","Collaborative Palletizing Robot":"Robot collaborativo pallettizzazione"},"idealFor":["Carte alto valore","Carte sigillate anti-manomissione","Pacco premium carte collezione","Prodotti carte sensibili umidità"]},
    "banding": {"name":"Imballaggio con Fascette","subtitle":"Imballaggio con Fascette Carte","description":"Legatura ecologica con nastro carta — metodo più sostenibile per mazzi di carte. Usa materiale minimo mantenendo legatura sicura.","features":["Guida servomotore con controllo PLC e schermo tattile","Emissione automatica carte + legatura cintura in un'operazione","Controllo fotoelettrico per erogazione e legatura automatica","Impostazioni multiple: quantità carte, materiale, allarme cintura","Spessore prodotto: 0,1–3 mm","Dimensione max prodotto: 100×150 mm"],"processSteps":{"1":"Conteggio alimentatore a frizione","2":"Macchina fascettatura","3":"Imballaggio manuale","4":"Macchina confezionamento scatole","5":"Disimballatrice","6":"Sigillascatola a H","7":"Robot collaborativo pallettizzazione"},"lineComponents":{"Friction Feeder":"Alimentatore a frizione","Banding Machine":"Macchina fascettatura","Cartoning Machine":"Macchina confezionamento scatole","Unpacking Machine":"Disimballatrice","H-Type Carton Sealer":"Sigillascatola a H","Collaborative Palletizing Robot":"Robot collaborativo pallettizzazione"},"idealFor":["Mazzi carte da tavolo","Mazzi carte da gioco standard","Imballaggio carte ecologico","Bundle multimaglia"]},
    "heat-shrink": {"name":"Imballaggio Termocontrazione","subtitle":"Imballaggio Termocontrazione Carte","description":"Avvolgimento con pellicola termocontratta aderente — offre visibilità 360° del prodotto con eccellente protezione. La pellicola aderisce stretta al profilo del prodotto.","features":["Fotoelettrico importato rilevamento per piccoli/piccoli imballaggi","Alimentazione automatica con occhio elettrico +调节lunghezza timer","Protezione automatica lama saldatura da tagli accidentali","Meccanismo sincronizzazione pellicola sopra/sotto corregge deviazione","Regolabile direzione aria calda per belle linee di saldatura"],"processSteps":{"1":"Conteggio alimentatore a frizione","2":"Macchina incarto flow","3":"Forno termocontrazione","4":"Confezionamento manuale scatole","5":"Imballaggio in casi","6":"Disimballatrice","7":"Sigillascatola a H","8":"Robot collaborativo pallettizzazione"},"lineComponents":{"Friction Feeder":"Alimentatore a frizione","Flow Packing Machine":"Macchina incarto flow","Shrinking Machine":"Forno termocontrazione","Cartoning Machine":"Macchina confezionamento scatole","Unpacking Machine":"Disimballatrice","H-Type Carton Sealer":"Sigillascatola a H","Collaborative Palletizing Robot":"Robot collaborativo pallettizzazione"},"idealFor":["Bundle multipack scatole carte","Presentazioni pronte vendita","Imballaggio trasparente esposizione","Prodotti pronti scaffale"]},
    "three-dimensional": {"name":"Imballaggio Tridimensionale","subtitle":"Imballaggio Tridimensionale Carte","description":"Avvolgimento 3D stile scatola — crea una confezione rigida simile a una scatola da un singolo foglio di film. Presentazione premium con bordi netti e sensazione solida.","features":["Crea imballaggio rigido simile a scatola da film piatto","Bordi netti e presentazione premium","Adatto a prodotti spessi (fino a 65 mm altezza)","Controllo servomotore per qualità costante","PLC programmabile con interfaccia schermo tattile"],"processSteps":{"1":"Conteggio alimentatore a frizione","2":"Macchina imballaggio tridimensionale","3":"Confezionamento manuale scatole","4":"Imballaggio in casi","5":"Disimballatrice","6":"Sigillascatola a H","7":"Robot collaborativo pallettizzazione"},"lineComponents":{"Friction Feeder":"Alimentatore a frizione","Three-Dimensional Packaging Machine":"Macchina imballaggio tridimensionale","Cartoning Machine":"Macchina confezionamento scatole","Unpacking Machine":"Disimballatrice","H-Type Carton Sealer":"Sigillascatola a H","Collaborative Palletizing Robot":"Robot collaborativo pallettizzazione"},"idealFor":["Scatole collezione premium","Set regalo imballaggio carte","Presentazione prodotti alta gamma","Bundle edizione limitata"]}
}

# German
de_data = {
    "candy": {"name":"Bonbonverpackung","subtitle":"Karten-Bonbonverpackung","description":"Hochgeschwindigkeits-Kissenflussverpackung — die beliebteste Methode für Trading Card Game (TCG)-Booster Packs und Sammelkartenhüllen. Erzeugt eine versiegelte Bonbonverpackung mit bis zu 220 Beuteln/min.","features":["Servogesteuerte Beutelänge — einstellen und schneiden, kein Leerlauf","Hochempfindlicher Fotoelektrischer Sensor für präzises Versiegeln","Bis zu 60 Verpackungsparametervoreinstellungen am HMI","Fehlbedienungsschutz: automatische Umkehr bei Produktwechsel","Automatischer Stopp ohne Folie zur Vermeidung von Verschwendung"],"processSteps":{"1":"Reibungs-Zählvorgabe","2":"Flussverpackungsmaschine","3":"Wägekontrolle (NG-Aussortierung)","4":"Manuelle Kartonierung","5":"Fallenverpackung","6":"Schrumpffolie","7":"H-förmiger Kartonversiegelung","8":"Kollaborativer Palettierroboter"},"lineComponents":{"Friction Feeder":"Reibungsförderer","Flow Packing Machine":"Flussverpackungsmaschine","Sealing & Cutting Shrinkage Machine":"Versiegelungs- und Schneidschrumpfmaschine","Unpacking Machine":"Entpackungsmaschine","H-Type Carton Sealer":"H-förmiger Kartonversiegeler","Collaborative Palletizing Robot":"Kollaborativer Palettierroboter"},"idealFor":["TCG-Booster-Packs","Sammelkartenhüllen","Spielkarten-Multipacks","Promotionale Kartenbündel"]},
    "self-adhesive": {"name":"Selbstklebeband-Verpackung","subtitle":"Karten-Selbstklebeband-Verpackung","description":"Wiederverschließbare Selbstklebeband-Beutel — ideal für Premium-Kartenprodukte mit Wiederverschließbarkeit. Jeder Beutel verfügt über eine Abzieh-Streifen für wiederholtes Öffnen und Schließen.","features":["Drei Versiegelungsmethoden: selbstklebend, Heißschnitt oder Heißpresse","Automatische Korrektur zur Reduzierung von Verpackungsverlusten","Leerbeutel-Erkennung — kein Material, kein Folienverschwendung","Freie Einstellung der Beutelbreite für Multi-Spez-Produkte","Ein-Klick-Reset und bidirektionale Positionssteuerung","Punktgedächtnis für genaues Zählen und Batch-Verpackung"],"processSteps":{"1":"Reibungs-Zählvorgabe","2":"Beutelverfüllungsmaschine","3":"Manuelle Kartonierung","4":"Versiegelung und Schrumpfschnitt","5":"Fallenverpackung","6":"H-förmiger Kartonversiegelung","7":"Kollaborativer Palettierroboter"},"lineComponents":{"Friction Feeder":"Reibungsförderer","Bagging Machine":"Beutelverfüllungsmaschine","Sealing & Cutting Shrinkage Machine":"Versiegelungs- und Schneidschrumpfmaschine","Unpacking Machine":"Entpackungsmaschine","H-Type Carton Sealer":"H-förmiger Kartonversiegeler","Collaborative Palletizing Robot":"Kollaborativer Palettierroboter"},"idealFor":["Premium-Sammlersätze","Wiederverschließbare Lagerbeutel für Karten","Verkaufsanzeige-Kartenpacks","Limitierte Edition Kartenbündel"]},
    "four-sides": {"name":"Vierseitige Versiegelungsverpackung","subtitle":"Karten-Vierseitige Versiegelungsverpackung","description":"Allseitige thermische Randversiegelung — Premium-Darstellung gegen Manipulation. Die vollständig versiegelten Ränder schützen vor Feuchtigkeit und Kontamination.","features":["Sieben Servomotoren für ultra-stabilen Betrieb","Dreifarbiges elektrisches Auge für präzise Text/Bild-Ausrichtung","Eindechniges hin-und her gehendes Schneiden und Thermoschweißen","Hochgeschwindigkeitsversiegelung — fest und stabil bei 150 Beuteln/min","Programmierbare PLC-Steuerung mit Touchscreen-HMI"],"processSteps":{"1":"Reibungs-Zählvorgabe","2":"Vierseitige Versiegelungsmaschine","3":"Kartoniervorrichtung","4":"Beutel- und Kastenverpackung","5":"Entpackungsmaschine","6":"H-förmiger Kartonversiegeler","7":"Kollaborativer Palettierroboter"},"lineComponents":{"Friction Feeder":"Reibungsförderer","Four-Side Sealing Packing Machine":"Vierseitige Versiegelungsmaschine","Cartoning Machine":"Kartoniervorrichtung","Unpacking Machine":"Entpackungsmaschine","H-Type Carton Sealer":"H-förmiger Kartonversiegeler","Collaborative Palletizing Robot":"Kollaborativer Palettierroboter"},"idealFor":["Hochwertige Handelskarten","Manipulationsgesicherte versiegelte Karten","Premium-Sammlerkartenpakete","Feuchtigkeitsempfindliche Kartenprodukte"]},
    "banding": {"name":"Bandverpackung","subtitle":"Karten-Bandverpackung","description":"Umweltfreundliches Papierband-Bündeln — nachhaltigste Verpackungsmethode für Kartenspiele. Verwendet minimales Material bei sicherem Bündeln.","features":["Servomotorantrieb mit PLC-Steuerung und Touchscreen","Automatische Kartenausgabe + Bandbindung in einem Vorgang","Fotoelektrische Steuerung für automatische Ausgabe und Bündeln","Vielfache Funktionseinstellungen: Kartenzahl, Material, Bandalarm","Produktdickenbereich: 0,1–3 mm","Max Produktgröße: 100×150 mm"],"processSteps":{"1":"Reibungs-Zählvorgabe","2":"Bindemaschine","3":"Manuelle Packung","4":"Kartoniervorrichtung","5":"Entpackungsmaschine","6":"H-förmiger Kartonversiegeler","7":"Kollaborativer Palettierroboter"},"lineComponents":{"Friction Feeder":"Reibungsförderer","Banding Machine":"Bindemaschine","Cartoning Machine":"Kartoniervorrichtung","Unpacking Machine":"Entpackungsmaschine","H-Type Carton Sealer":"H-förmiger Kartonversiegeler","Collaborative Palletizing Robot":"Kollaborativer Palettierroboter"},"idealFor":["Brettspielkartenspiele","Standard-Spielkarten","Umweltfreundliche Kartenverpackung","Mehrdeck-Kartenbündel"]},
    "heat-shrink": {"name":"Schrumpfverpackung","subtitle":"Karten-Schrumpfverpackung","description":"Eng anliegende Schrumpfolien-Umhüllung — bietet 360° Produktsichtbarkeit bei hervorragendem Schutz. Die Folie passt sich eng dem Produktprofil an.","features":["Importierter Fotoelektrischer Detektor für dünne/kleine Verpackungen","Automatische Zufuhr mit Elektroauge + Timer-Längeneinstellung","Automatischer Messerschutz vor versehentlichen Schnitten","Folien-Synchronisationsmechanismus oben/unten korrigiert Abweichung","Einstellbare heiße Luft-Richtung für schöne Schweißnähte"],"processSteps":{"1":"Reibungs-Zählvorgabe","2":"Flussverpackungsmaschine","3":"Schrumpfofen","4":"Manuelle Kartonierung","5":"Fallenverpackung","6":"Entpackungsmaschine","7":"H-förmiger Kartonversiegeler","8":"Kollaborativer Palettierroboter"},"lineComponents":{"Friction Feeder":"Reibungsförderer","Flow Packing Machine":"Flussverpackungsmaschine","Shrinking Machine":"Schrumpfofen","Cartoning Machine":"Kartoniervorrichtung","Unpacking Machine":"Entpackungsmaschine","H-Type Carton Sealer":"H-förmiger Kartonversiegeler","Collaborative Palletizing Robot":"Kollaborativer Palettierroboter"},"idealFor":["Kartenschachtel-Multipack-Bündel","Einzelhandelsfertige Präsentationen","Transparente Displayverpackung","Regalbereite Kartenprodukte"]},
    "three-dimensional": {"name":"3D-Verpackung","subtitle":"Karten-3D-Verpackung","description":"Kastenförmiges 3D-Umschlagen — erstellt eine steife kastenähnliche Verpackung aus einem einzelnen Folienblatt. Premium-Präsentation mit scharfen Kanten und festem Gefühl.","features":["Erzeugt steife kastenähnliche Verpackung aus flacher Folie","Scharfe Kanten und Premium-Präsentation","Geeignet für dicke Produkte (bis 65 mm Höhe)","Servogesteuert für konsistente Qualität","Programmierbar PLC mit Touchscreen-Oberfläche"],"processSteps":{"1":"Reibungs-Zählvorgabe","2":"3D-Verpackungsmaschine","3":"Manuelle Kartonierung","4":"Fallenverpackung","5":"Entpackungsmaschine","6":"H-förmiger Kartonversiegeler","7":"Kollaborativer Palettierroboter"},"lineComponents":{"Friction Feeder":"Reibungsförderer","Three-Dimensional Packaging Machine":"3D-Verpackungsmaschine","Cartoning Machine":"Kartoniervorrichtung","Unpacking Machine":"Entpackungsmaschine","H-Type Carton Sealer":"H-förmiger Kartonversiegeler","Collaborative Palletizing Robot":"Kollaborativer Palettierroboter"},"idealFor":["Premium-Sammlerkartonschateln","Geschenkset-Kartenverpackung","High-End-Produktpräsentation","Limitierte Edition Kartenbündel"]}
}

# French
fr_data = {
    "candy": {"name":"Emballage Bonbon","subtitle":"Emballage Bonbon Cartes","description":"Emballage par flux à coussin haute vitesse — la méthode la plus populaire pour les boosters de jeux de cartes à collectionner (TCG) et les housses de protection de cartes. Produit un emballage scellé type bonbon jusqu'à 220 sachets/min.","features":["Longueur de sachet contrôlée par servomoteur — régler et couper, pas de course à vide","Capteur photoélectrique haute sensibilité pour un scellage précis","Jusqu'à 60 préréglages de paramètres d'emballage sur IHM","Protection contre les erreurs : inversion automatique au changement de produit","Arrêt automatique sans film pour éviter le gaspillage"],"processSteps":{"1":"Comptage par alimentation friction","2":"Machine d'emballage flux","3":"Contrôle poids (rejet NG)","4":"Mise en cartons manuelle","5":"Mise en caisses","6":"Thermo-rétraction","7":"Ferme-carton en H","8":"Robot collaboratif palettisation"},"lineComponents":{"Friction Feeder":"Alimentateur friction","Flow Packing Machine":"Machine emballage flux","Sealing & Cutting Shrinkage Machine":"Machine scellage et découpe rétractable","Unpacking Machine":"Désemballeuse","H-Type Carton Sealer":"Ferme-carton H","Collaborative Palletizing Robot":"Robot collaboratif palettisation"},"idealFor":["Boosters TCG","Housses protection cartes","Multipacks cartes jeu","Lots promotionnels"]},
    "self-adhesive": {"name":"Emballage Bande Auto-adhésive","subtitle":"Emballage Bande Auto-adhésive Cartes","description":"Sachets refermables avec bande auto-adhésive — idéaux pour produits cartes premium nécessitant référmabilité. Chaque sachet dispose d'une bande à décoller-refermer pour ouverture et fermeture répétée.","features":["Trois méthodes de scellage : auto-adhésif, coupe chaude ou presse chaude","Correction automatique pour réduire pertes d'emballage","Détection sachets vides — pas de matériel, pas de perte film","Largeur de sachet librement ajustable pour produits multi-spec","Reset en un clic et contrôle position bidirectionnel","Mémoire point pour comptage précis et conditionnement lot"],"processSteps":{"1":"Comptage par alimentation friction","2":"Machine mise en sachets","3":"Mise en cartons manuelle","4":"Scellage et découpe rétractable","5":"Mise en caisses","6":"Ferme-carton en H","7":"Robot collaboratif palettisation"},"lineComponents":{"Friction Feeder":"Alimentateur friction","Bagging Machine":"Machine mise en sachets","Sealing & Cutting Shrinkage Machine":"Machine scellage et découpe rétractable","Unpacking Machine":"Désemballeuse","H-Type Carton Sealer":"Ferme-carton H","Collaborative Palletizing Robot":"Robot collaboratif palettisation"},"idealFor":["Sets collection premium","Sachets stockage refermables cartes","Packs affichage vente","Éditions limitées lots"]},
    "four-sides": {"name":"Emballage Quatre Côtés Scellés","subtitle":"Emballage Quatre Côtés Scellés Cartes","description":"Scellage thermique des quatre bords — présentation premium anti-effraction. Les bords complètement scellés protègent contre humidité et contamination.","features":["Sept servomoteurs pour fonctionnement ultra-stable","Oeil électrique tricolore pour alignement texte/image précis","Technologie unique de découpe et soudure thermique alternante","Scellage haute vitesse — ferme et stable à 150 sachets/min","Contrôle PLC programmable avec écran tactile IHM"],"processSteps":{"1":"Comptage par alimentation friction","2":"Machine scellage quatre côtés","3":"Machine cartonnage","4":"Mise en sachets et cartons","5":"Désemballeuse","6":"Ferme-carton en H","7":"Robot collaboratif palettisation"},"lineComponents":{"Friction Feeder":"Alimentateur friction","Four-Side Sealing Packing Machine":"Machine scellage quatre côtés","Cartoning Machine":"Machine cartonnage","Unpacking Machine":"Désemballeuse","H-Type Carton Sealer":"Ferme-carton H","Collaborative Palletizing Robot":"Robot collaboratif palettisation"},"idealFor":["Cartes haute valeur","Cartes scellées anti-effraction","Packs premium collection cartes","Produits cartes sensibles humidité"]},
    "banding": {"name":"Emballage Cerclage","subtitle":"Emballage Cerclage Cartes","description":"Cerclage écologique en papier — méthode la plus durable pour jeux de cartes. Utilise un minimum de matériau tout en maintenant un cerclage sécurisé.","features":["Entraînement servomoteur avec contrôle PLC et écran tactile","Distribution automatique cartes + ceinturage en une opération","Contrôle photoélectrique pour distribution et cerclage automatiques","Paramètres multiples : quantité cartes, matériau, alarme bande","Gamme épaisseur produit : 0,1–3 mm","Taille max produit : 100×150 mm"],"processSteps":{"1":"Comptage par alimentation friction","2":"Machine ceinturage","3":"Conditionnement manuel","4":"Machine cartonnage","5":"Désemballeuse","6":"Ferme-carton en H","7":"Robot collaboratif palettisation"},"lineComponents":{"Friction Feeder":"Alimentateur friction","Banding Machine":"Machine ceinturage","Cartoning Machine":"Machine cartonnage","Unpacking Machine":"Désemballeuse","H-Type Carton Sealer":"Ferme-carton H","Collaborative Palletizing Robot":"Robot collaboratif palettisation"},"idealFor":["Jeux de cartes plateau","Jeux de cartes standard","Emballage cartes écologique","Paquets multi-jeux"]},
    "heat-shrink": {"name":"Emballage Thermo-rétractable","subtitle":"Emballage Thermo-rétractable Cartes","description":"Enroulement serré en film thermo-rétractable — offre une visibilité à 360° du produit avec excellente protection. Le film se moule étroitement au contour du produit.","features":["Capteur photoélectrique importé pour petits/emballages fins","Alimentation automatique avec oeil électrique + réglage longueur minuterie","Protection automatique lame de scellage contre coupures accidentelles","Mécanisme synchronisation film haut/bas corrige déviation","Réglable direction air chaud pour belles lignes de soudure"],"processSteps":{"1":"Comptage par alimentation friction","2":"Machine emballage flux","3":"Four thermo-rétraction","4":"Mise en cartons manuelle","5":"Mise en caisses","6":"Désemballeuse","7":"Ferme-carton en H","8":"Robot collaboratif palettisation"},"lineComponents":{"Friction Feeder":"Alimentateur friction","Flow Packing Machine":"Machine emballage flux","Shrinking Machine":"Four thermo-rétraction","Cartoning Machine":"Machine cartonnage","Unpacking Machine":"Désemballeuse","H-Type Carton Sealer":"Ferme-carton H","Collaborative Palletizing Robot":"Robot collaboratif palettisation"},"idealFor":["Multipacks boîtes cartes","Présentations prêtes vente","Emballage transparent exposition","Produits prêts rayon"]},
    "three-dimensional": {"name":"Emballage 3D","subtitle":"Emballage 3D Cartes","description":"Enroulement 3D style boîte — crée un emballage rigide semblable à une boîte à partir d'une seule feuille de film. Présentation premium avec bords nets et sensation solide.","features":["Crée un emballage rigide style boîte à partir de film plat","Bords nets et présentation premium","Adapté aux produits épais (jusqu'à 65 mm hauteur)","Contrôle servomoteur pour qualité constante","PLC programmable avec interface écran tactile"],"processSteps":{"1":"Comptage par alimentation friction","2":"Machine emballage 3D","3":"Mise en cartons manuelle","4":"Mise en caisses","5":"Désemballeuse","6":"Ferme-carton en H","7":"Robot collaboratif palettisation"},"lineComponents":{"Friction Feeder":"Alimentateur friction","Three-Dimensional Packaging Machine":"Machine emballage 3D","Cartoning Machine":"Machine cartonnage","Unpacking Machine":"Désemballeuse","H-Type Carton Sealer":"Ferme-carton H","Collaborative Palletizing Robot":"Robot collaboratif palettisation"},"idealFor":["Boîtes collection premium","Sets cadeau cartes emballage","Présentation produits haut de gamme","Éditions limitées"]},
}

# Spanish
es_data = {
    "candy": {"name":"Embalaje Caramelo","subtitle":"Embalaje Caramelo Tarjetas","description":"Embalaje flujo tipo almohada de alta velocidad — el método más popular para los boosters de juegos de cartas coleccionables (TCG) y fundas protectoras de tarjetas. Produce un envoltorio sellado tipo caramelo hasta 220 bolsas/min.","features":["Longitud de bolsa controlada por servomotor — ajustar y cortar sin recorrido vacío","Sensor fotoeléctrico de alta sensibilidad para sellado preciso","Hasta 60 preajustes de parámetros de embalaje en IHM","Protección contra errores: inversión automática al cambiar producto","Parada automática sin película para evitar desperdicio"],"processSteps":{"1":"Conteo por alimentación por fricción","2":"Máquina embalaje flujo","3":"Control de peso (rechazo NG)","4":"Embalaje manual en cajas","5":"Embalaje en casos","6":"Termorretracción","7":"Sellador de cajas tipo H","8":"Robot colaborativo paletizado"},"lineComponents":{"Friction Feeder":"Alimentador por fricción","Flow Packing Machine":"Máquina embalaje flujo","Sealing & Cutting Shrinkage Machine":"Máquina sellado y corte retráctil","Unpacking Machine":"Desembaladora","H-Type Carton Sealer":"Sellador de cajas tipo H","Collaborative Palletizing Robot":"Robot colaborativo paletizado"},"idealFor":["Boosters TCG","Fundas protectoras de tarjetas","Multipacks de tarjetas de juego","Lotes promocionales"]},
    "self-adhesive": {"name":"Embalaje con Banda Autoadhesiva","subtitle":"Embalaje con Banda Autoadhesiva Tarjetas","description":"Bolsas recerrables con banda autoadhesiva — ideales para productos de tarjetas premium que requieren re-sellabilidad. Cada bolsa cuenta con una tira despegable-pegar para apertura y cierre repetidos.","features":["Tres métodos de sellado: autoadhesivo, corte caliente o prensa caliente","Corrección automática para reducir pérdidas de embalaje","Detección de bolsas vacías — sin material, sin pérdida de película","Anchura de bolsa libremente ajustable para productos multi-spec","Reset de un clic y control de posición bidireccional","Memoria de puntos para conteo preciso y embalaje por lotes"],"processSteps":{"1":"Conteo por alimentación por fricción","2":"Máquina ensacado","3":"Embalaje manual en cajas","4":"Sellado y corte retráctil","5":"Embalaje en casos","6":"Sellador de cajas tipo H","7":"Robot colaborativo paletizado"},"lineComponents":{"Friction Feeder":"Alimentador por fricción","Bagging Machine":"Máquina ensacado","Sealing & Cutting Shrinkage Machine":"Máquina sellado y corte retráctil","Unpacking Machine":"Desembaladora","H-Type Carton Sealer":"Sellador de cajas tipo H","Collaborative Palletizing Robot":"Robot colaborativo paletizado"},"idealFor":["Sets de colección premium","Bolsas de almacenamiento re-cerrables","Packs de exhibición en venta","Ediciones limitadas"]},
    "four-sides": {"name":"Embalaje Cuatro Lados Sellado","subtitle":"Embalaje Cuatro Lados Sellado Tarjetas","description":"Sellado térmico de los cuatro bordes — presentación premium anti-manipulación. Los bordes completamente sellados protegen contra humedad y contaminación.","features":["Siete servomotores para operación ultraestable","Ojo eléctrico tricolor para alineación precisa texto/imagen","Tecnología única de corte y soldadura recíproca","Sellado de alta velocidad — firme y estable a 150 bolsas/min","Control PLC programable con pantalla táctil IHM"],"processSteps":{"1":"Conteo por alimentación por fricción","2":"Máquina sellado cuatro lados","3":"Máquina encajonado","4":"Ensacado y encajonado","5":"Desembaladora","6":"Sellador de cajas tipo H","7":"Robot colaborativo paletizado"},"lineComponents":{"Friction Feeder":"Alimentador por fricción","Four-Side Sealing Packing Machine":"Máquina sellado cuatro lados","Cartoning Machine":"Máquina encajonado","Unpacking Machine":"Desembaladora","H-Type Carton Sealer":"Sellador de cajas tipo H","Collaborative Palletizing Robot":"Robot colaborativo paletizado"},"idealFor":["Tarjetas de alto valor","Tarjetas selladas anti-manipulación","Packs premium de colección","Productos de tarjetas sensibles a humedad"]},
    "banding": {"name":"Embalaje con Fleje","subtitle":"Embalaje con Fleje Tarjetas","description":"Flejado ecológico con papel — método más sostenible para mazos de tarjetas. Usa mínimo material manteniendo flejado seguro.","features":["Acción de servomotor con control PLC y pantalla táctil","Emisión automática de tarjetas + flejado con cinta en una operación","Control fotoeléctrico para emisión y flejado automáticos","Ajustes múltiples: cantidad tarjetas, material, alarma cinta","Rango espesor producto: 0,1–3 mm","Tamaño máximo producto: 100×150 mm"],"processSteps":{"1":"Conteo por alimentación por fricción","2":"Máquina flejado","3":"Embalaje manual","4":"Máquina encajonado","5":"Desembaladora","6":"Sellador de cajas tipo H","7":"Robot colaborativo paletizado"},"lineComponents":{"Friction Feeder":"Alimentador por fricción","Banding Machine":"Máquina flejado","Cartoning Machine":"Máquina encajonado","Unpacking Machine":"Desembaladora","H-Type Carton Sealer":"Sellador de cajas tipo H","Collaborative Palletizing Robot":"Robot colaborativo paletizado"},"idealFor":["Mazos de juegos de mesa","Barajas estándar","Embalaje ecológico de tarjetas","Lotes multi-baraja"]},
    "heat-shrink": {"name":"Embalaje Termorretráctil","subtitle":"Embalaje Termorretráctil Tarjetas","description":"Envoltorio ajustado con película termorretráctil — ofrece visibilidad 360° del producto con excelente protección. La película se ajusta firmemente al contorno del producto.","features":["Detector fotoeléctrico importado para embalajes pequeños/delgados","Alimentación automática con ojo eléctrico + ajuste longitud temporizador","Protección automática de cuchillo de soldado contra cortes accidentales","Mecanismo de sincronización película arriba/abajo corrige desviación","Dirección aire caliente ajustable para líneas de soldado hermosas"],"processSteps":{"1":"Conteo por alimentación por fricción","2":"Máquina embalaje flujo","3":"Horno termorretracción","4":"Embalaje manual en cajas","5":"Embalaje en casos","6":"Desembaladora","7":"Sellador de cajas tipo H","8":"Robot colaborativo paletizado"},"lineComponents":{"Friction Feeder":"Alimentador por fricción","Flow Packing Machine":"Máquina embalaje flujo","Shrinking Machine":"Horno termorretracción","Cartoning Machine":"Máquina encajonado","Unpacking Machine":"Desembaladora","H-Type Carton Sealer":"Sellador de cajas tipo H","Collaborative Palletizing Robot":"Robot colaborativo paletizado"},"idealFor":["Multipacks de cajas de tarjetas","Presentaciones listas para venta","Embalaje transparente exhibición","Productos listos para estantería"]},
    "three-dimensional": {"name":"Embalaje 3D","subtitle":"Embalaje 3D Tarjetas","description":"Envoltorio 3D estilo caja — crea un empaque rígido similar a caja desde una sola hoja de película. Presentación premium con bordes definidos y sensación sólida.","features":["Crea empaque rígido similar a caja desde película plana","Bordes definidos y presentación premium","Adecuado para productos gruesos (hasta 65 mm altura)","Control servomotor para calidad constante","PLC programable con interfaz pantalla táctil"],"processSteps":{"1":"Conteo por alimentación por fricción","2":"Máquina embalaje 3D","3":"Embalaje manual en cajas","4":"Embalaje en casos","5":"Desembaladora","6":"Sellador de cajas tipo H","7":"Robot colaborativo paletizado"},"lineComponents":{"Friction Feeder":"Alimentador por fricción","Three-Dimensional Packaging Machine":"Máquina embalaje 3D","Cartoning Machine":"Máquina encajonado","Unpacking Machine":"Desembaladora","H-Type Carton Sealer":"Sellador de cajas tipo H","Collaborative Palletizing Robot":"Robot colaborativo paletizado"},"idealFor":["Cajas de colección premium","Sets regalo empaque tarjetas","Presentación productos alta gama","Ediciones limitadas"]}
}

# Korean
ko_data = {
    "candy": {"name":"캔디 포장","subtitle":"카드 캔디 포장","description":"고속 필로우래핑 방식 — TCG 부스터팩 및 컬렉션 카드 슬리브에 가장 인기 있는 방식. 분당 최대 220봉투의 캔디형 밀봉 포장을 생산합니다.","features":["서보제어 봉투 길이 — 설정 및 절단, 빈 행정 없음","고감도 광전센서 추적으로 정밀 밀봉","HMI에 저장되는 최대 60개 포장 파라미터 프리셋","오작동 방지: 제품 교체 시 자동 역회전","필름 없음 자동 정지로 낭비 방지"],"processSteps":{"1":"마찰 급지 계수","2":"플로우 포장 기계","3":"중량검사(NG 배출)","4":"수동 카톤닝","5":"케이스 패킹","6":"수축포장","7":"H형 카톤 실러","8":"협업 팔레타이징 로봇"},"lineComponents":{"Friction Feeder":"마찰 급지기","Flow Packing Machine":"플로우 포장 기계","Sealing & Cutting Shrinkage Machine":"밀봉 절단 수축 기계","Unpacking Machine":"언패킹 머신","H-Type Carton Sealer":"H형 카톤 실러","Collaborative Palletizing Robot":"협업 팔레타이징 로봇"},"idealFor":["TCG 부스터팩","컬렉션 카드 슬리브","게임 카드 멀티팩","프로모 카드 번들"]},
    "self-adhesive": {"name":"자접착 테이프 포장","subtitle":"카드 자접착 테이프 포장","description":"재밀봉 가능한 자접착 테이프 봉투 — 재밀봉이 필요한 프리미엄 카드 제품에 적합합니다. 각 봉투는 반복 개폐용 벗김-붙임 스트립이 있습니다.","features":["세 가지 밀봉 방식: 자접착, 핫컷 또는 핫프레스","자동 보정으로 포장 손실 감소","빈 봉투 감지 — 재료 없음, 필름 낭비 없음","멀티 스펙 제품에 자유롭게 조절 가능한 봉투 폭","원클릭 리셋 및 양방향 위치 제어","정확한 계수 및 배치 포장을 위한 점 기억"],"processSteps":{"1":"마찰 급지 계수","2":"봉투 충전 기계","3":"수동 카톤닝","4":"밀봉 절단 수축","5":"케이스 패킹","6":"H형 카톤 실러","7":"협업 팔레타이징 로봇"},"lineComponents":{"Friction Feeder":"마찰 급지기","Bagging Machine":"봉투 충전 기계","Sealing & Cutting Shrinkage Machine":"밀봉 절단 수축 기계","Unpacking Machine":"언패킹 머신","H-Type Carton Sealer":"H형 카톤 실러","Collaborative Palletizing Robot":"협업 팔레타이징 로봇"},"idealFor":["프리미엄 컬렉션 세트","재밀봉 가능한 카드 저장 봉투","매장 전시 카드 팩","한정판 번들"]},
    "four-sides": {"name":"4면 밀봉 포장","subtitle":"카드 4면 밀봉 포장","description":"4변 열 밀봉 포장 — 프리미엄 위조방지 프레젠테이션을 제공합니다. 완전 밀봉된 모서리는 습기와 오염으로부터 보호합니다.","features":["7개 서보모터로 초안정 작동","3색 전기 눈 정밀 텍스트/이미지 정렬","독특한 왕복 절단 및 열 용접 기술","고속 밀봉 — 분당 150봉투에서도 견고하고 안정적","터치스크린 HMI가 있는 프로그램 가능한 PLC 제어"],"processSteps":{"1":"마찰 급지 계수","2":"4면 밀봉 기계","3":"카톤닝 기계","4":"봉투 및 카톤닝","5":"언패킹 머신","6":"H형 카톤 실러","7":"협업 팔레타이징 로봇"},"lineComponents":{"Friction Feeder":"마찰 급지기","Four-Side Sealing Packing Machine":"4면 밀봉 기계","Cartoning Machine":"카톤닝 기계","Unpacking Machine":"언패킹 머신","H-Type Carton Sealer":"H형 카톤 실러","Collaborative Palletizing Robot":"협업 팔레타이징 로봇"},"idealFor":["고가치 거래 카드","위조방지 밀봉 카드","프리미엄 컬렉션 카드 팩","습기에 민감한 카드 제품"]},
    "banding": {"name":"밴딩 포장","subtitle":"카드 밴딩 포장","description":"친환경 종이 밴드 묶음 — 카드 덱 포장에 가장 지속 가능한 방식. 최소 자재로 안전한 묶음을 유지합니다.","features":["PLC 제어 및 터치스크린 서보모터 구동","자동 카드 발행 + 벨트 묶음 일회 작업","광전기 제어 자동 발급 및 묶음","다기능 설정: 카드 수량, 재료, 밴드 알람","제품 두께 범위: 0.1–3mm","최대 제품 크기: 100×150mm"],"processSteps":{"1":"마찰 급지 계수","2":"밴딩 기계","3":"수동 패킹","4":"카톤닝 기계","5":"언패킹 머신","6":"H형 카톤 실러","7":"협업 팔레타이징 로봇"},"lineComponents":{"Friction Feeder":"마찰 급지기","Banding Machine":"밴딩 기계","Cartoning Machine":"카톤닝 기계","Unpacking Machine":"언패킹 머신","H-Type Carton Sealer":"H형 카톤 실러","Collaborative Palletizing Robot":"협업 팔레타이징 로봇"},"idealFor":["보드게임 카드 덱","표준 플레잉카드 덱","친환경 카드 포장","멀티덱 번들"]},
    "heat-shrink": {"name":"수축 포장","subtitle":"카드 수축 포장","description":"꼭 맞는 수축 필름 포장 — 우수한 보호성과 함께 360° 제품 가시성을 제공합니다. 수축 필름은 제품 윤곽에 밀착합니다.","features":["얇은/작은 포장용 수입 광전 검출기","전기 눈 + 타이머 길이 조정 자동 급지","실수 절단 방지 날 자동 보호","필름 상하 동기화 메커니즘 편차 수정","아름다운 용접선을 위한 조절 가능한 열풍 방향"],"processSteps":{"1":"마찰 급지 계수","2":"플로우 포장 기계","3":"수축로","4":"수동 카톤닝","5":"케이스 패킹","6":"언패킹 머신","7":"H형 카톤 실러","8":"협업 팔레타이징 로봇"},"lineComponents":{"Friction Feeder":"마찰 급지기","Flow Packing Machine":"플로우 포장 기계","Shrinking Machine":"수축로","Cartoning Machine":"카톤닝 기계","Unpacking Machine":"언패킹 머신","H-Type Carton Sealer":"H형 카톤 실러","Collaborative Palletizing Robot":"협업 팔레타이징 로봇"},"idealFor":["카드 박스 멀티팩 번들","판매 준비 프레젠테이션","투명 디스플레이 포장","선반 준비 제품"]},
    "three-dimensional": {"name":"3차원 포장","subtitle":"카드 3차원 포장","description":"박스형 3D 포장 — 한 장의 평면 필름으로 단단한 박스형 포장을 만듭니다. 날카로운 모서리와 단단한 느낌의 프리미엄 프레젠테이션입니다.","features":["평면 필름에서 단단한 박스형 포장 생성","날카로운 모서리와 프리미엄 프레젠테이션","두꺼운 제품 적합(최대 65mm 높이)","일관된 품질을 위한 서보 제어","터치스크린 인터페이스가 있는 프로그램 가능한 PLC"],"processSteps":{"1":"마찰 급지 계수","2":"3차원 포장 기계","3":"수동 카톤닝","4":"케이스 패킹","5":"언패킹 머신","6":"H형 카톤 실러","7":"협업 팔레타이징 로봇"},"lineComponents":{"Friction Feeder":"마찰 급지기","Three-Dimensional Packaging Machine":"3차원 포장 기계","Cartoning Machine":"카톤닝 기계","Unpacking Machine":"언패킹 머신","H-Type Carton Sealer":"H형 카톤 실러","Collaborative Palletizing Robot":"협업 팔레타이징 로봇"},"idealFor":["프리미엄 수집 박스","선물 세트 카드 포장","하이엔드 제품 프레젠테이션","한정판 번들"]}
}

# Japanese
ja_data = {
    "candy": {"name":"キャンディ包装","subtitle":"カード キャンディ包装","description":"高速ピロー流し包装 — TCGブスターパックやコレクションカードスリーブで最も人気のある方式。分間最大220袋のシール済みキャンディ包装を生産。","features":["サーボ制御袋長さ — 設定・切断、空走りなし","高感度光電センサー追跡で精密封締","HMIに最大60個の包装パラメータプリセット保存","誤動作防止：製品切替時自動逆回転","フィルム切れ自動停止で無駄防止"],"processSteps":{"1":"摩擦給紙計数","2":"フロー包装機","3":"検量（NG排出）","4":"手動梱包","5":"ケース梱包","6":"シュリンクラップ","7":"H型箱詰機","8":"協働パレタイジロボット"},"lineComponents":{"Friction Feeder":"摩擦給紙機","Flow Packing Machine":"フロー包装機","Sealing & Cutting Shrinkage Machine":"封締・切断収縮機","Unpacking Machine":"開梱機","H-Type Carton Sealer":"H型箱詰機","Collaborative Palletizing Robot":"協働パレタイジロボット"},"idealFor":["TCGブスターパック","コレクションカードスリーブ","ゲームカードマルチパック","プロモーションカードバンドル"]},
    "self-adhesive": {"name":"自己粘着ストリップ包装","subtitle":"カード 自己粘着ストリップ包装","description":"再封可能な自己粘着ストリップ袋 — 再密封が必要なプレミアムカード製品に最適。各袋には繰り返し開閉できる剥がし・貼りストリップ搭載。","features":["3種の封締方式：自己粘着、ホットカット、またはホットプレス","自動補正で包装損失低減","空袋検知 — 材料なし、フィルム無駄なし","多仕様製品対応の自由調整可能な袋幅","ワンクリックリセットと双方向位置制御","精密計数とバッチ包装のためのポイント記憶"],"processSteps":{"1":"摩擦給紙計数","2":"袋詰め機","3":"手動梱包","4":"封締・切断収縮","5":"ケース梱包","6":"H型箱詰機","7":"協働パレタイジロボット"},"lineComponents":{"Friction Feeder":"摩擦給紙機","Bagging Machine":"袋詰め機","Sealing & Cutting Shrinkage Machine":"封締・切断収縮機","Unpacking Machine":"開梱機","H-Type Carton Sealer":"H型箱詰機","Collaborative Palletizing Robot":"協働パレタイジロボット"},"idealFor":["プレミアムコレクションセット","再封可能なカード保管袋","店舗陳列用カードパック","限定エディションバンドル"]},
    "four-sides": {"name":"四方シール包装","subtitle":"カード 四方シール包装","description":"四面全熱シール包装 — プレミアムな改ざん防止プレゼンテーションを提供。完全にシールされた端は湿気と汚染から保護。","features":["7つのサーボモーターで超安定稼働","3色電気アイで精密テキスト/画像位置合わせ","独自の往復切断・熱溶接技術","高速シール — 分間150袋でも堅牢で安定","タッチスクリーンHMI付きプログラム可能PLC制御"],"processSteps":{"1":"摩擦給紙計数","2":"四方シール機","3":"自動梱包機","4":"袋詰め・箱詰め","5":"開梱機","6":"H型箱詰機","7":"協働パレタイジロボット"},"lineComponents":{"Friction Feeder":"摩擦給紙機","Four-Side Sealing Packing Machine":"四方シール機","Cartoning Machine":"自動梱包機","Unpacking Machine":"開梱機","H-Type Carton Sealer":"H型箱詰機","Collaborative Palletizing Robot":"協働パレタイジロボット"},"idealFor":["高価値トレーディングカード","改ざん防止シールカード","プレミアムコレクションカードパック","湿気敏感カード製品"]},
    "banding": {"name":"バンディング包装","subtitle":"カード バンディング包装","description":"環境に優しい紙バンド結束 — カードデッキ包装で最も持続可能な方式。最小材料で安全な結束を実現。","features":["PLC制御とタッチスクリーンのサーボモータ駆動","自動カード発行＋ベルト結束一括作業","光電気制御による自動発行と結束","複数機能設定：カード数量、素材、ベルトアラーム","製品厚範囲：0.1–3mm","最大製品サイズ：100×150mm"],"processSteps":{"1":"摩擦給紙計数","2":"バンディング機","3":"手動梱包","4":"自動梱包機","5":"開梱機","6":"H型箱詰機","7":"協働パレタイジロボット"},"lineComponents":{"Friction Feeder":"摩擦給紙機","Banding Machine":"バンディング機","Cartoning Machine":"自動梱包機","Unpacking Machine":"開梱機","H-Type Carton Sealer":"H型箱詰機","Collaborative Palletizing Robot":"協働パレタイジロボット"},"idealFor":["ボードゲームカードデッキ","標準プレイングカードデッキ","環境配慮型カード包装","マルチデッキバンドル"]},
    "heat-shrink": {"name":"熱収縮包装","subtitle":"カード 熱収縮包装","description":"密着型シュリンクフィルム包装 — 優れた保護性と共に360°製品可視性を提供。シュリンクフィルムは製品輪郭に密着。","features":["薄い／小さい包装向け輸入光電検出器","電気アイ＋タイマー長さ調整付き自動給送","ナイフ誤切り防止自動保護","フィルム上下同期機構で偏差修正","美しいシールラインのための調節可能な熱風方向"],"processSteps":{"1":"摩擦給紙計数","2":"フロー包装機","3":"シュリンク炉","4":"手動梱包","5":"ケース梱包","6":"開梱機","7":"H型箱詰機","8":"協働パレタイジロボット"},"lineComponents":{"Friction Feeder":"摩擦給紙機","Flow Packing Machine":"フロー包装機","Shrinking Machine":"シュリンク炉","Cartoning Machine":"自動梱包機","Unpacking Machine":"開梱機","H-Type Carton Sealer":"H型箱詰機","Collaborative Palletizing Robot":"協働パレタイジロボット"},"idealFor":["カードボックスマルチパックバンドル","小売準備完了プレゼンテーション","透明ディスプレイ包装","棚設置可能製品"]},
    "three-dimensional": {"name":"3次元包装","subtitle":"カード 3次元包装","description":"ボックス型3Dラッピング — 1枚の平らなフィルムから剛直なボックス状包装を作成。シャープなエッジとしっかりした手触りのプレミアムプレゼンテーション。","features":["平らなフィルムから剛直なボックス状包装を生成","シャープなエッジとプレミアムプレゼンテーション","厚い製品対応（最大高さ65mm）","一貫した品質のためのサーボ制御","タッチスクリーンインターフェース付きプログラム可能PLC"],"processSteps":{"1":"摩擦給紙計数","2":"3次元包装機","3":"手動梱包","4":"ケース梱包","5":"開梱機","6":"H型箱詰機","7":"協働パレタイジロボット"},"lineComponents":{"Friction Feeder":"摩擦給紙機","Three-Dimensional Packaging Machine":"3次元包装機","Cartoning Machine":"自動梱包機","Unpacking Machine":"開梱機","H-Type Carton Sealer":"H型箱詰機","Collaborative Palletizing Robot":"協働パレタイジロボット"},"idealFor":["プレミアムコレクションボックス","ギフトセットカード包装","ハイエンド製品プレゼンテーション","限定エディションバンドル"]}
}

translations = {'en': en_data, 'ru': ru_data, 'it': it_data, 'de': de_data,
              'fr': fr_data, 'es': es_data, 'ko': ko_data, 'ja': ja_data}

for lang, data in translations.items():
    path = f'{base_dir}/{lang}.json'
    with open(path, 'r', encoding='utf-8') as f:
        content = json.load(f)
    
    if 'solutions' in content:
        content['solutions']['solutionsData'] = data
    
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(content, f, ensure_ascii=False, indent=2)
    
    print(f'{lang}: OK')

print('All done!')
